apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  labels:
    service: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
        service: search-service
  template:
    metadata:
      name: search-service
      labels:
        service: search-service
    spec:
      containers:
        - name: search-service
          image: search-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7070
              protocol: TCP
      restartPolicy: Always

      #apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: title
#  labels:
#    app: title
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: title
#  template:
#    metadata:
#      name: title
#      labels:
#        app: title
#    spec:
#      containers:
#        - name: title
#          image: nginx
#          imagePullPolicy: IfNotPresent
#          ports:
#            - containerPort: 80
#              protocol: TCP
#      restartPolicy: Always
      