apiVersion: v1
kind: Service
metadata:
  name: search-svc
  labels:
    service: service-svc
spec:
  selector:
    service: search-service
  type: NodePort
  ports:
    - port: 7070
      targetPort: 7070
      nodePort: 30070
      protocol: TCP