pipeline{
	agent any
	environment {
		IMAGE_TAG = 'search-service-${env.BUILD_NUMBER}'
	}
	stages{
		stage('Checkout SCM') {
			steps {
				script {
					def gitUrl = scm.getUserRemoteConfigs()[0].getUrl()
					def gitBranch = scm.getBranches()[0].getName()
					echo "Git URL: ${gitUrl}"
					echo "Git Branch: ${gitBranch}"
					git url: gitUrl, branch: gitBranch, credentialsId: 'github-pat'
				}
			}
		}

		stage('Build service') {
			steps {
				echo "Building the service..."
				sh 'mvn clean package -DskipTests'
			}
		}

		stage('Test service') {
			steps {
				echo "Running tests..."
				sh 'mvn test'
			}
		}

		stage('Deploy service') {
			steps {
				sh 'docker build -t search-service-${env.BUILD_NUMBER} search-service'
			}
		}

		stage('Expose docker image to Kubernetes') {
			steps {
				sh 'minikube image load search-service-${env.BUILD_NUMBER}'
			}
		}
	}

	post{
		success{
			echo "Pipeline completed successfully!"
		}
		failure{
			echo "Pipeline failed. Please check the logs for details."
		}
	}
}