pipeline{
	agent any
	environment {
		GIT_REPO = 'https://github.com/gitneo/qryos-1.git'
		APP_NAME = 'search-service'
		GIT_BRANCH = '${env.BRANCH_NAME}'
		IMAGE_TAG = "${env.BUILD_NUMBER}"
		GIT_URL = "${env.GIT_URL}"
	}
	stages{
		stage('Checkout Repository') {
			steps {
				echo "Checking out the repository..."
				git url: 'https://github.com/gitneo/bookstore.git', branch:'${GIT_BRANCH}', credentialsId: 'github-pat'
			}
		}

		stage('Build service') {
			steps {
				echo "Building the service..."
				sh 'mvn clean package -DskipTests'
			}
		}

		stage('Test service') {
			steps {
				echo "Running tests..."
				sh 'mvn test'
			}
		}

		stage('Deploy service') {
			steps {
				sh 'docker build -t ${APP_NAME}-${IMAGE_TAG} search-service'
			}
		}

		stage('Expose docker image to Kubernetes') {
			steps {
				sh 'minikube image load ${APP_NAME}:lane-${IMAGE_TAG}'
			}
		}
	}

	post{
		success{
			echo "Pipeline completed successfully!"
		}
		failure{
			echo "Pipeline failed. Please check the logs for details."
		}
	}
}